#!/bin/sh

ssh victor@linbuntu <<EOF
  cd ~/work/nobckup/bb/jenkins/hello-jenkins
  git pull
  npm install #--production
  #npm install forever #victor needs su 2 run but not jenkins! Y?
  #forever restartall
  node app.js &
  exit
EOF
