#!/bin/sh

ssh victor@linbuntu <<EOF
  cd ~/work/nobckup/bb/jenkins/hello-jenkins
  git pull
  echo npm install
  npm install #--production
  echo nmp install forever commented out
  #npm install forever #victor needs su 2 run but not jenkins! Y?
  #forever restartall

  #this runs in bckgnd aft xit called!!! so we sleep 3s bf callg xit
  echo node app.js in bckgnd
  node app.js &

  sleep 3
  echo exit
  exit
EOF
